#!/bin/bash

source ./config.sh

response_pipe="$MAIN_DIR${$}"


while true
do 
    if [[ ! -p $PIPE ]]; then
        echo "the mainPipe doesn't exists"
        break
    fi

    echo -n "enter command name: "
    read command_name

    request="BEGIN-REQ $$: $command_name END-REQ"


    if [[ ! -p $PIPE ]]; then
        echo "the mainPipe doesn't exists"
        break
    else
        echo "$request" >$PIPE
    fi
    

    while [[ ! -p "$response_pipe" ]] 
    do
        sleep 0.05
    done

    cat "$response_pipe"
    
    rm -f $response_pipe

done